name: Watch Analyzer and Flowise Every Minute

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every minute

  workflow_dispatch:  # Allows manual triggering

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Make HTTP request to Analyzer
        run: curl -X GET "https://analyzer-sczh.onrender.com"

      - name: Make HTTP request to Flowise
        run: curl -X GET "https://flowise-7wwo.onrender.com"

      - name: Make HTTP request to locadata
        run: curl -X GET "https://locadata.onrender.com"
